language: node_js
node_js:
- stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- npm test
- npm run doc
after_success:
- jsdoc/publish.sh
env:
  global:
    secure: "Bx6pW0ihp3Y2dW5a8fkPhbMKsVg7MRfCzN3laN/OL7vTy2etIDXFleddE5No74HVQ1gPhkOIoRko/pHPdzWGNq69VtoCxp3AdISsuillYcaDCfRXDBSZXbHVuXsUHFQIABIdKJZZVjjwXM4oulL4OWboZ8FWV7vgOBvN4ZrXjM8LfuahSG51cPbPktqa+v/rA03iuWwC8IUDhf5w2uNPrsvtzWmj+CHcpLIgjmJWan+SiJXK/i3Wz/B74Cb0RtP9Y7zJzIGSWg8Z1VruN/f8xoNeSbMz5HM+PMhGyQJ9QXUNEqUEiXG+gwIzhAYRwBbCGyQZME5zk/y7QM0lr3/4NBzq8e6RYWlyOVLRGxlL6SvPmQ/6FrMCe9QDcMnvDvfeYhTHa6SnkqymN1hp1JnPC65zXENbEOLJH/67mQs/WoHLuuZycUK0KPC+GK6Bc45ViXotyNTttzrxHfpOV4IXQDVqB6p6tlh940ksYpetSs+8s7piUOGIcu4XtYxdnSRGX7TwKiCuuK65XWYpk+oMWhKHsOS2FTDt85+PXKFnM1fiuFD+Oppa7xyXmSUZp4C1befd7nP7F5RGSkZWdfXuCY6xAS6E7dho4clIua2yhOWtgnoMlcjjht6sFYf8OEk3eoVvnP+OO3VSHwk0VkTbI3E3fp3H8CUXVMk9woegydQ="
